--This place is used for database transformation scripts. 
--For example you want to edit db schema, but this changes will reflect only new created instanses
-- you should to support update of already created databses. You can do it in two ways. Such script file or db migrations.